export const alertOptions = {
  error: {
    title: 'Error',
    message: 'Please choose a date in the future',
    color: '#EF4040',
    position: 'topRight',
    icon: 'icon-octagon',
    iconText: '',
    timeout: 5000,
    titleColor: '#fff',
    messageColor: '#fff',
    iconColor: '#fff',
  },
  success: {
    title: 'OK',
    message: 'Fulfilled promise in 4000ms',
    color: '#59A10D',
    position: 'topRight',
    icon: 'icon-check-circle',
    iconText: '',
    timeout: 5000,
    titleColor: '#fff',
    messageColor: '#fff',
    iconColor: '#fff',
  },
};
